version: "3.8"

services:
  # 1. The Web Server (React + Nginx)
  client:
    build: ./client
    ports:
      - "80:80" # Exposed to the public
    depends_on:
      - server

  # 2. The Game Logic (Go)
  server:
    build: ./backend
    expose:
      - "8080" # Only internal access (Nginx talks to this)
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    volumes:
      - ./data:/data # PERSISTENCE: Maps VM folder ./data to container /data

  # 3. The Cache (Redis)
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
